### ISSUE TITLE
How far have you come?

### ISSUE THREAD

**Issue by riccardoklinger** [kxtells/kxtells_qgis_plugins#1]
I will need this functionality for my @qgis2leaf plugin and I was writing a qgis2.2 version of this for my own. Can I help you with something? Just open an issue

**Comment by kxtells** [comment]
Hi

I did not have time to try in different situations, nor to set the plugin
to work with threads (so it does not block qgis when writing to the layer).

I worked with the Natural Earth countries dataset using the three main
types of symbol coloring.

Salut!

_--Castells--_
http://jcastellssala.wordpress.com

**Comment by kxtells** [comment]
Closing this since it's extremely old and the qgis2.x version is already on the repo.
